require("options")
require("launch")

spec("plugin.colors")
spec("plugin.treesitter")
spec("plugin.telescope")
spec("plugin.oil")
spec("plugin.lspzero")
spec("plugin.mason")
spec("plugin.leap")
spec("plugin.devicons")
spec("plugin.gitsigns")
spec("plugin.unception")

require("plugin.lazy")
require("keybindings")
